# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: pt-br

pipeline:
    - name: SpacyNLP
      model: "pt_core_news_sm"
    - name: WhitespaceTokenizer
    - name: CountVectorsFeaturizer
    - name: CountVectorsFeaturizer
      analyzer: char_wb
      min_ngram: 1
      max_ngram: 12
    # - name: CRFEntityExtractor
    - name: SpacyEntityExtractor
      dimensions: ["LOC"]
    - name: DIETClassifier
      epochs: 100
      model_confidence: softmax
      constrain_similarities: True
    - name: FallbackClassifier
      threshold: 0.6
      ambiguity_threshold: 0.1

policies:
    - name: RulePolicy
    - name: MemoizationPolicy
    - name: TEDPolicy
      max_history: 5
      epochs: 50
      constrain_similarities: True
